//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskConsoleApp.Resources.ConfigConstants", typeof(ConfigConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppConfig.
        /// </summary>
        internal static string AppConfigSection {
            get {
                return ResourceManager.GetString("AppConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        internal static string AppSettingsFileName {
            get {
                return ResourceManager.GetString("AppSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load application configuration from appsettings.json.
        /// </summary>
        internal static string ConfigAppLoadFailureMessage {
            get {
                return ResourceManager.GetString("ConfigAppLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load logging configuration from appsettings.json.
        /// </summary>
        internal static string ConfigLogLoadFailureMessage {
            get {
                return ResourceManager.GetString("ConfigLogLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get serviceProvider from configuring services.
        /// </summary>
        internal static string ConfiguringServicesFailureMessages {
            get {
                return ResourceManager.GetString("ConfiguringServicesFailureMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy HH:mm:ss.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string ErrorOccuredFailureMessage {
            get {
                return ResourceManager.GetString("ErrorOccuredFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing line &apos;{0}&apos;: &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorParsingLineFailureMessage {
            get {
                return ResourceManager.GetString("ErrorParsingLineFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file &apos;{0}&apos;: &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorReadingFileFailureMessage {
            get {
                return ResourceManager.GetString("ErrorReadingFileFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to parse line &apos;{0}&apos;. Error: &apos;{1}&apos;.
        /// </summary>
        internal static string FailedToParseLineWarningMessage {
            get {
                return ResourceManager.GetString("FailedToParseLineWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: &apos;{0}&apos;.
        /// </summary>
        public static string FileNotFoundFailureMessage {
            get {
                return ResourceManager.GetString("FileNotFoundFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string LogConfigSection {
            get {
                return ResourceManager.GetString("LogConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No input file path provided..
        /// </summary>
        internal static string NoInputFileFailureMessage {
            get {
                return ResourceManager.GetString("NoInputFileFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy} {1}.
        /// </summary>
        internal static string ReportService_PrintFirstReport__0_dd_MM_yyyy___1_ {
            get {
                return ResourceManager.GetString("ReportService_PrintFirstReport__0_dd_MM_yyyy___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to src folder not found..
        /// </summary>
        internal static string SrcFileNotFoundFailureMessage {
            get {
                return ResourceManager.GetString("SrcFileNotFoundFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace session starting.
        /// </summary>
        internal static string TraceSessionStartingMessage {
            get {
                return ResourceManager.GetString("TraceSessionStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception: .
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unobserved Exception: .
        /// </summary>
        internal static string UnobservedTaskExceptionMessage {
            get {
                return ResourceManager.GetString("UnobservedTaskExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing trace log to .
        /// </summary>
        internal static string WritingTraceToLogMessage {
            get {
                return ResourceManager.GetString("WritingTraceToLogMessage", resourceCulture);
            }
        }
    }
}
